var rzeczy = [
        ["oglądałem pokemony", "oglądałem uśmiechniętą mysz, która pika jak serce"],
        ["grałem na pegasusie", "grałem w dziesięc gier na jednym kartridżu"],
        ["układałem klocki lego", "układałem wysoką wieżę, budowałem swój świat"],
        ["wiązałem najki air force 1", "wiązałem buty, miałem pod nogami świat"],
        ["grałem na xboksie 360", "grałem w reżyserską wersję halo 3, zabijałem złych"],
        ["jadłem laysy zielona cebulka", "jadłem czipsy, docieplałem swój brzuch"],
        ["grałem na playstation 4", "grałem w god of war 3, zabijałem złych"],
        ["grałem na xboksie one", "grałem w america's army, ratowałem świat"],
        ["oglądałem youtube na surface 3", "oglądałem uśmiechnięte koty, które miauczą przez sen"],
        ["oglądałem vimeo na ipadzie air", "oglądałem uśmiechnięte pieski, które warczą przez sen"],
        ["grałem w magic the gathering", "tasowałem karty wysp, bagien, lasów i pól"],
        ["odpakowywałem snickersa", "zagryzałem batona, żeby mieć siłę do życia"],
        ["odkręcałem coca colę", "nalewałem colę do szklanki na colę i dorzucałem lód"],
        ["oglądałem gwiezdne wojny", "oglądałem robota, który pika jak serce"],
        ["grałem w team fortress 2", "podpalałem szpiegów, którzy kradli nam skarby"],
        ["jadłem laysy czerwona papryka", "jadłem czipsy, kaleczyłem nimi język i dziąsła"],
        ["jadłem laysy klasycznne solone", "jadłem czipsy, nakładałem je na język jak chleb"],
        ["ugniatałem ciastolinę play-doh", "formowałem z masy słońce, książyc i psa"],
        ["grałem w minecrafta", "budowałem portal, żeby wejść do piekła"],
        ["grałem w mortal kombat", "chciałem być dobry, więc rozdawałem ciosy"],
        ["grałem w the sims 3", "sprzedawałem drzwi i okna, żeby mieć na schody"],
        ["grałem w gta vice city", "strzelałem do ludzi, żeby zabić czas"],
        ["grałem w half-life", "byłem naukowcem, który ratował planetę"],
        ["grałem w world of warcraft", "zbierałem doświadczenie, zabijałem bestie"],
        ["bawiłem się tamagotchi", "karmiłem piksele zjadające baterię"], // CO
        ["układałem puzzle", "układałem wieżę eiffla, żeby mieć co zniszczyć"],
        ["grałem na ibm pc", "grałem w wolfensteina, zabijałem złych"],
        ["grałem w magię i miecz", "tasowałem karty przygód, planowałem podróż"],
        ["oglądałem spidermana", "oglądałem człowieka przyklejonego do szklanki"],
        ["oglądałem władcę pierścieni", "oglądałem ludzi ceniących biżuterię wyżej niż życie"],
        ["grałem w monopoly", "kupowałem kraje europy, wodociągi i kolej"],
        ["zdalnie sterowałem terenówką", "przemierzałem przedpokój, uczyłem się granic"],
        ["układałem klocki cobi", "układałem dom i ogród, budowałem swój świat"],
        ["układałem klocki playmobil", "układałem komisariat policji, budowałem swój świat"],
        ["żułem gumę mamba", "miałem mambę, ty miałaś, oni mieli"],
        ["grałem w lego gwiezdne wojny", "rozbijałem roboty, które strzelały mi w serce"]
    ],
    bomby = [
        ["pierwszy samolot", "uderzał w północną wieżę world trade center", "drugi samolot", "uderzał w południową wieżę world trade center"],
        ["eksplodowały", "dwa pociągi na madryckiej stacji atocha", "eksplodowały", "dwa pociągi za madrycką stacją atocha"],
        ["wybuchały", "bomby w londyńskim metrze linii piccadilly", "wybuchały", "bomby w londyńskim autobusie routemaster"],
        ["wybuchały", "bomby w jazdzyckiej al-kahtanijji", "wybuchały", "bomby w jazydzkiej dżazirze"],
        ["tamilskie tygrysy", "porywały policjantów z batticaloa", "tamilskie tygrysy", "mordowały policjantów z batticaloa"],
        ["eksplodowały", "bomby na przystanku w as-saura", "eksplodowały", "bomby w stolicy, a później całym iraku"],
        ["barykadowano", "widzów kina cinema rex w abadanie", "podpalano", "widzów kina cinema rex w abadanie"],
        ["boko haram", "zanosiło śmierć do gamboru", "boko haram", "zanosiło śmierć do ngali"],
        ["eksplodowała", "bomba na pokładzie lotu air india 182", "eksplodowała", "bomba na lotnisku międzynarodowym tokio narita"],
        ["terroryści", "podjechali ciężarówką pod szkołę w biesłanie", "antyterroryści", "podjechali czołgiem pod szkołę w biesłanie"],
        ["pierwsza ciężarówka", "uderzała w koszary sił pokojowych w bejrucie", "druga ciężarówka", "uderzała w koszary sił pokojowych w bejrucie"],
        ["wybuchała", "bomba w sklepie przy moskiewskim placu maneżowym", "wybuchała", "bomba w bloku przy moskiewskiej ulicy gurjanowa"],
        ["lot pan am 103", "eksplodował na niebie nad szkockim lockerbie", "lot pan am 103", "spadał na mieszkańców szkockiego lockerbie"],
        ["wybuchały", "bomby w hotelu sea rock, centaur juhu i airport", "wybuchały", "bomby na bazarach zaveri, katha i century"],
        ["lot metrojet 9268", "rozpadał się w powietrzu na dwoje", "lot metrojet 9268", "rozbijał się na skalistej pustyni synaju"],
        ["wybuchała", "ciężarówka pod ambasadą stanów w nairobi", "wybuchała", "ciężarówka pod ambasadą stanów w dar es salaam"],
        ["zamachowcy", "wchodzili do ratusza miejscowości mubi", "zamachowcy", "wchodzili do kościoła w miejscowości yola"],
        ["pierwszy pocisk", "spadał na mieszkańców dzielnicy as-saura", "drugi pocisk", "spadał na mieszkańców dzielnicy as-saura"],
        ["eksplodowały", "pociągi przy mumbajskiej stacji andheri", "eksplodowały", "pociągi przy mumbajskiej stacji matunga"],
        ["wybuchała", "bomba przed klubem paddy's pub na bali", "wybuchała", "bomba przed klubem sari club na bali"],
        ["wybuchały", "bomby w czasie aszury w karbali", "wybuchały", "bomby w czasie aszury w bagdadzie"],
        ["lot uta 772", "eksplodował w locie nad saharą", "lot uta 772", "rozbijał się w piaskach sahary"],
        ["pierwsza ciężarówka", "wybuchała w tal afar w iraku", "druga ciężarówka", "wybuchała w tal afar w iraku"],
        ["pierwsza bomba", "wybuchała pośród pielgrzymów w al-hilla", "druga bomba", "wybuchała pośród pielgrzymów w al-hilla"],
        ["samobójca", "wysadzał się w tłumie w mieście ghalbiyah", "samobójca", "wysadzał się w tłumie w mieście bakuba"],
        ["wybuchały", "bomby na rynku w maiduguri", "wybuchały", "bomby na rynku w monguno"],
        ["pierwsza bomba", "wybuchała przed dworcem w ankarze", "druga bomba", "wybuchała przed dworcem w ankarze"],
        ["wybuchała", "bomba na pokładzie volga-aviaexpress 1353", "wybuchała", "bomba na pokładzie siberia airlines 1047"],
        ["pierwszy samochód", "wybuchał w sercu osiedla bab al-shariq", "drugi samochód", "wybuchał w sercu osiedla bab al-shariq"],
        ["eksplodowała", "bomba na starym rynku w szarm el-szejk", "eksplodowała", "bomba w hotelu moevenpick w szarm el-szejk"],
        ["pierwsza samobójczyni", "wysadzała się w bagdackim meczecie buratha", "druga samobójczyni", "wysadzała się w bagdackim meczecie buratha"],
        ["wybuchała", "bomba w zachodnim bagdadzie", "wybuchała", "bomba we wschodnim bagdadzie"],
        ["pierwszy samobójca", "wysadzał się przed meczetem w chanakin", "drugi samobójca", "wysadzał się przed meczetem w chanakin"],
        ["zamachowiec", "wysadzał się w restauracji ethiopian village w kampali", "zamachowiec", "wysadzał się w klubie rugby kyadondo"],
        ["pierwszy samochód", "eksplodował w czasie minuty ciszy w bagdadzie", "drugi samochód", "eksplodował w czasie minuty ciszy w bagdadzie"],
        ["neonazista", "strzelał do dzieci na wyspie utoya", "neonazista", "wysadzał samochód przed biurem premiera norwegii"],
        ["eksplodowały", "bomby na bazarach bari, johari i tripolia", "eksplodowały", "bomby na posterunku manak chowk w jaipurze"],
        ["pierwszy samochód", "wybuchał przez meczetem alego w an-nadżafie", "drugi samochód", "wybuchał przed meczetem alego w an-nadżafie"],
        ["eksplodowały", "bomby w guwathi i barpeta road", "eksplodowały", "bomby w bongaigaon i kokrajhar"],
        ["eksplodowały", "samochody-pułapki w starym mieście basry", "eksplodowały", "samochody-pułapki w dzielnicy ashar"],
        ["zamachowiec-samobójca", "wysadzał się w powietrze w bagdadzie", "zamachowiec-samobójca", "wysadzał się w powietrze w al-mikdadija"],
        ["eksplodowały", "ładunki wybuchowe na royal artillery bazaar", "eksplodowały", "ładunki wybuchowe na rynku w iqbal town"],
        ["pierwszy samobójca", "wysadzał się w fabryce broni w wah", "drugi samobójca", "wysadzał się w fabryce broni w wah"],
        ["eksplodował", "pierwszy wagon samjhauta express za stacją diwana", "eksplodował", "drugi wagon samjhauta express za stacją diwana"],
        ["samochód-pułapka", "eksplodował na pogrzebie w an-nadżafie", "samochód-pułapka", "eksplodował na dworcu w karbali"],
        ["eksplodowała", "bomba w hotelu grand hyatt w ammanie", "eksplodowała", "bomba w hotelu radisson sas w ammanie"],
        ["pierwszy samobójca", "wysadzał się w obozie dla uchodźców w kohat", "drugi samobójca", "wysadzał sie w obozie dla uchodźców w kohat"],
        ["pierwsza ciężarówka", "wjeżdżała w synagogę w stambule", "druga ciężarówka", "wjeżdżała w synagogę w stambule"],
        ["pierwszy samochód", "wybuchał w mieście reyhanli w turcji", "drugi samochód", "wybuchał w mieście reyhanli w turcji"]
    ],
    maksimumRzecz = rzeczy.length,
    maksimumBomba = bomby.length;
